Opt: Refactor module enhancement
LmeSzinc/AzurLaneAutoScript pull request #963
Opened 2022-03-11 18:09 UTC by Horizon101011

#777 
对_enhance_choose()进行了细化和重构：
- 新增_enhance_recommend()，完成强化素材的设置和初步识别
通过该方法可区分无素材和有素材，对于无素材情况直接判定强化失败
- 使用强化空槽代替info_bar作为特征，并进行二值化的模板匹配，具备更强的抗干扰性
- 由于不再使用info_bar，移除了所有和info_bar相关的部分

目前的调用逻辑是，enhance_ships调用_enhance_choose进行强化
_enhance_choose确保推荐按钮出现，随后调用_enhance_recommend点击推荐并进行初次识别
随后点击确定并根据后续结果，点掉成功弹窗或滑动切换，返回到强化界面

Button和Template类中都加入了match_binary()方法，二值化采用自适应阈值

2022-03-12 02:43 UTC, LmeSzinc commented on module/retire/enhancement.py
> +                return True, True
点击-等待 的模式在 Alas 里是禁止的。
点击和获取结果需要各自独立，点击靠 appear_then_click(interval=2) 每两秒触发一次，获取结果实时返回
直接返回 string 就好了，更直观，未来有新的状态也容易调整

2022-03-12 02:43 UTC, LmeSzinc commented on module/retire/enhancement.py
> +                    self.device.screenshot()
同样是 点击-等待，这是禁止的

2022-03-12 02:43 UTC, LmeSzinc commented on module/base/template.py
> +            _, sim, _, _ = cv2.minMaxLoc(res)
将 self_image_binary 缓存下来，不用每次识别都算一次

2022-03-12 02:43 UTC, LmeSzinc commented on module/retire/enhancement.py
> +                    continue
滑动到下一个的判断条件还是应该从另一个函数当中获取，不是到最后剩下的就是失败了

2022-03-12 02:52 UTC, LmeSzinc commented
#942 里提到的内容没有完全做到。旧强化模块的主要问题是：不靠实时识别然后操作，只是对各种情况想当然地处理；这个 PR 仍然是同样的问题。

2022-03-12 15:57 UTC, Horizon101011 commented on module/retire/enhancement.py
> +                    self.device.screenshot()
已修改

2022-03-12 15:58 UTC, Horizon101011 commented on module/base/template.py
> +            _, sim, _, _ = cv2.minMaxLoc(res)
把image_gray和image_binary都做了缓存，用于灰度匹配（未来如果需要的话）和二值匹配

2022-03-12 15:59 UTC, Horizon101011 commented on module/retire/enhancement.py
> +                    continue
新的commit将这部分抽出来做了状态函数，但不确定是否能达成你期望的结果

2022-03-12 16:02 UTC, Horizon101011 commented on module/retire/enhancement.py
> +                return True, True
新的commit使用了DFA的形式，将整个强化过程分解成了若干子状态函数，通过状态函数的返回值来确定状态机的转移。DFA的形式也方便扩展或者调整。

2022-03-12 16:18 UTC, Horizon101011 commented
不是很确定你说的实时识别然后操作是一个怎么样的效果

我先说一下我对新改动的思路：
整个强化过程可以被拆分成若干个子状态，如条件检查、推荐、强化、失败等等
所以我用了DFA的形式，直接根据state来执行对应的状态函数，并且每一个函数几乎是只有一个动作的

所以基于这种形式，整个处理过程是异步的，比如一个典型的强化成功操作，它的状态走向应该是这样的
state_enhance_check -> state_enhance_ready -> state_enhance_recommend -> state_enhance_attempt -> 
state_enhance_confirm -> state_enhance_success
对应的动作流是：
检查基准条件 -> 确认推荐按钮出现并点击 -> 确认强化素材出现 -> 确认确定按钮出现并点击 -> 
确认出现装备分解的弹窗并处理 -> 强化成功

就我个人的角度，这是我能想到的最优办法，对不同情况的处理只需要修改状态函数的返回值就能完成

2022-03-12 17:04 UTC, Horizon101011 commented
这里再贴一下DFA的转移函数，如果有什么状态或者情况遗漏方便补充

state_enhance_success 和 state_enhance_exit是终末状态，标识强化是否成功
初始状态是state_enhance_check
以[state, condition] = state(, action) 的形式给出

1. [state_enhance_check, 到达强化数量] = state_enhance_exit    （退出强化）
2. [state_enhance_check, 状态栏未出现] = state_enhance_check （条件检查）
3. [state_enhance_check, 推荐按钮出现] = state_enhance_ready （强化就绪）
4. [state_enhance_ready, 推荐按钮出现] = state_enhance_recommend, 点击推荐按钮
5. [state_enhance_ready, 推荐按钮未出现] = state_enhance_ready
6. [state_enhance_recommend, 检测到空槽(无素材)] = state_enhance_fail （无素材，强化失败）
7. [state_enhance_recommend, 未检测到空槽(有素材)] = state_enhance_attempt （尝试强化）
8. [state_enhance_attempt, 确定按钮出现] = state_enhance_confirm, 点击确定按钮
9. [state_enhance_attempt, 确定按钮未出现] = state_enhance_attempt
10. [state_enhance_confirm, 装备弹窗出现] = state_enhance_success, 处理所有弹窗
11. [state_enhance_confirm, 装备弹窗未出现] = state_enhance_fail （战斗中，强化失败）
12. [state_enhance_fail, 滑动成功] = state_enhance_check （进入下一次强化前的检查）
13. [state_enhance_fail, 滑动失败] = state_enhance_exit （退出强化）
***
下面是对网络波段或设备问题引起的截图问题的一些说明。这里假设点击操作是正常的
>  5 [state_enhance_ready, 推荐按钮未出现] = state_enhance_ready
> 9 [state_enhance_attempt, 确定按钮未出现] = state_enhance_attempt

对状态项5和9，网络波动或设备问题会引起自陷，这意味着如果断网这里会进入死循环
判断用的是appear_then_click，按你说的这个函数会定时点击实时返回，所以应该会抛出too many click异常，但我不确定

> 6 [state_enhance_recommend, 检测到空槽(无素材)] = state_enhance_fail （无素材，强化失败）
> 7 [state_enhance_recommend, 未检测到空槽(有素材)] = state_enhance_attempt （尝试强化）

对于状态项6和7，由于使用空槽来识别，这样的方法会更加激进
由网络波动或者设备问题引起的误识别会进入尝试强化状态，但不影响运行
无素材的情况下进入尝试强化最终会流向强化失败，尽管原因应该是无素材而非战斗中

> 10 [state_enhance_confirm, 装备弹窗出现] = state_enhance_success, 处理所有弹窗
> 12 [state_enhance_fail, 滑动成功] = state_enhance_check （进入下一次强化前的检查）

状态项10和12的处理沿用了之前的 self._enhance_confirm() 和滑动的逻辑，对意外的处理和以前一致
self._enhance_confirm() 包含了一系列的弹窗，如有必要可以拆分
***
接下来则是对引起操控问题的说明，即点击被吞掉
>4 [state_enhance_ready, 推荐按钮出现] = state_enhance_recommend, 点击推荐按钮
 
这里的推荐被吞掉，等同于没有选择任何素材，最终流向无素材失败

>8 [state_enhance_attempt, 确定按钮出现] = state_enhance_confirm, 点击确定按钮

这里的确定被吞掉，等同于战斗中无法强化，最终流向战斗中失败

上述两种情况如果同时出现，最终也是流向战斗中失败

>10 [state_enhance_confirm, 装备弹窗出现] = state_enhance_success, 处理所有弹窗
> 12 [state_enhance_fail, 滑动成功] = state_enhance_check （进入下一次强化前的检查）

这两项和上面一样，也是按原逻辑处理

2022-03-12 19:13 UTC, LmeSzinc requested changes

2022-03-12 19:13 UTC, LmeSzinc commented on module/retire/enhancement.py
> +                return True, True
这个函数没有用的的话，删掉吧

2022-03-13 02:21 UTC, Horizon101011 commented on module/retire/enhancement.py
> +        return state, ship_count
eval已修改

截图间隔似乎是必须的。至少在state_enhance_attempt -> state_enhance_confirm这里是需要的
如果没有必要的延时，点击确定强化之后到装备分解弹窗出现之前的这一段时间会导致误判
进入state_enhance_confirm之后会立刻因为还没有出现装备分解弹窗被判定为强化失败，但实际上是成功的

如果没有延时的话，这里似乎不太好处理，从逻辑上来说，state_enhance_confirm不需要等待某个东西出现之后再继续，这意味着不能自陷
其他部分是否会出现类似问题尚未测试，昨天发现这个问题之后图方便直接在这里设置了截图间隔

2022-03-15 13:59 UTC, Horizon101011 commented on module/retire/enhancement.py
> +        return state, ship_count
在state_enhance_confirm和state_enhance_recommend加了retry达成类似于自陷的效果

2022-03-15 17:15 UTC, LmeSzinc commented on module/retire/enhancement.py
> +                    break
这里是有问题的，不能保证 EQUIP_CONFIRM 或 info_bar_count() 在两次截图内必定出现
state_enhance_recommend 这样子可以，因为推荐按钮是全本地计算的，一张截图内就成功，就算是推荐成功被误判成推荐失败，也只是漏了一次强化而已。如果这里因为网络卡顿误判为 state_enhance_fail，后面弹出的 EQUIP_CONFIRM 弹窗不能处理。
还是要遵守 Alas 最基本的思想，不能等待

这个怪怪的，感觉就故意绕了一下
```python
for retry in range(1, 3):
```
如果只想循环两次，也不关心当前的循环次数的话，就用
```python
for _ in range(2):
```

2022-03-15 17:15 UTC, LmeSzinc commented on module/retire/enhancement.py
> +        return state, ship_count
存在不必要的 `self.device.screenshot()` 调用
每次循环调用一次，state_enhance_recommend 和 state_enhance_confirm 又在开头调用了一次

2022-03-15 17:16 UTC, LmeSzinc approved these changes

2022-03-16 01:08 UTC, Horizon101011 commented on module/retire/enhancement.py
> +                    break
暂时来说如果按当前特征来区分，误判问题是无法避免的
核心问题在于按下确定之后，强化成功和战斗中的转移条件不是稳定的
在按下确定之后，出现 EQUIP_CONFIRM 的一定是成功，但是多久才出现是无法确定的
state_enhance_recommend 也是一样的问题，但是他的危害会更轻

如果因为卡顿进入了 state_enhance_fail，即使我在头部加入 EQUIP_CONFIRM 的判断，依然没法确保在进入时就能看到
卡顿就像土豆电脑一样，如果刻意去适配是没有意义的
retry确实是一个等待的思想，在没有retry时处理速度太快了，以至于强化成功总会被误判为失败

写法问题是因为一开始retry有用但是后来放弃了

2022-03-16 01:12 UTC, Horizon101011 commented on module/retire/enhancement.py
> +        return state, ship_count
state_enhance_recommend 和 state_enhance_confirm 调用源自于对实现的不熟悉
因为不清楚 Button.match_binary(self.device.image)、self.appear()、self.info_bar_count() 会不会重新截图或者实时判断
如果他们都是直接从当前屏幕上重新识别的，那这两个状态里的截图可去

2022-03-16 14:29 UTC, LmeSzinc commented on module/retire/enhancement.py
> +        return state, ship_count
大部分 alas 方法都会复用上一张截图，这样连续调用的时候就不会产生多余的截图。每个任务开始的时候会先截一张图来启动。不操作游戏的方法内部没有截图

2022-03-24 09:59 UTC, Horizon101011 commented
recommend中加入了向ready的转移，confirm中加入了向attempt的转移，fail中加入了向confirm的转移

对于recommend，改动会使得alas一直点击推荐按钮直到 info_bar出现(无素材) 或 EMPTY_ENHANCE_SLOT不匹配(有素材)
去除了原有retry方式依然存在的误判漏判问题

对于confirm，改动会使得alas一直点击确定直到 info_bar出现(强化成功或失败) 或 EQUIP_CONFIRM出现(强化成功)
随后再根据EQUIP_CONFIRM判断是否成功，同样去除了原有方式的问题
另外，对于网络卡顿或者成功时info_bar 先于EQUIP_CONFIRM出现导致的fail误判，在fail中同样加入了判断
分别在进入fail的时候和尝试滑动失败之后判断EQUIP_CONFIRM

加入了状态转移上限的控制，从起始状态state_enhance_check开始最长的一次流程会有7次状态转移
如果在一次强化(无论失败或成功)过程中出现了20次以上的转移将抛出异常
实际运行中通常会因为处理速度过快而带来3-5次的额外转移
**在高配电脑上可能会因为处理速度过快导致更多的不必要的状态转移，需要测试**

2022-04-23 07:48 UTC, merged